/**
 * Blob storage abstraction (§7).
 *
 * Only ciphertext is ever written through this interface. Two properties are
 * non-negotiable regardless of backend:
 *
 *   1. Object keys are random and carry no filename (§14). A store listing must
 *      not reveal what the files are.
 *   2. The store is never inside a directory the gateway serves. Blobs reach a
 *      recipient only through the API, after a lease check — never as a static
 *      file (§14).
 */

export interface StorageAdapter {
  put(key: string, data: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  delete(key: string): Promise<void>;
  /** Remove a whole prefix (all chunks of an object). Returns count removed. */
  deletePrefix(prefix: string): Promise<number>;
  exists(key: string): Promise<boolean>;
  /** Total bytes stored, for the storage-pressure check (§18). */
  usedBytes(): Promise<number>;
  /** Enumerate keys under a prefix, for reconciliation (§19). */
  list(prefix: string): Promise<string[]>;
}

export class StorageError extends Error {
  override readonly name = 'StorageError';
  constructor(
    message: string,
    readonly code: 'not-found' | 'invalid-key' | 'io',
  ) {
    super(message);
  }
}

/**
 * Validate an object key.
 *
 * Keys are generated by this codebase, never by a client, but this check is the
 * backstop that keeps a path-traversal bug from becoming an arbitrary file
 * write. Only [A-Za-z0-9_-] segments separated by '/' are allowed, so '..',
 * absolute paths, NUL bytes and Windows device names are all rejected.
 */
export function assertValidKey(key: string): void {
  if (key.length === 0 || key.length > 512) {
    throw new StorageError('object key length out of range', 'invalid-key');
  }
  if (!/^[A-Za-z0-9_-]+(?:\/[A-Za-z0-9_-]+)*$/.test(key)) {
    throw new StorageError('object key contains disallowed characters', 'invalid-key');
  }
}

/** Chunk key for object `storageKey`, chunk `index`. */
export function chunkKey(storageKey: string, index: number): string {
  if (!Number.isInteger(index) || index < 0) {
    throw new StorageError(`invalid chunk index: ${index}`, 'invalid-key');
  }
  return `${storageKey}/c${index}`;
}

export { FilesystemStorage } from './filesystem.ts';
export { createStorage } from './factory.ts';
